# Generated by Django 5.2 on 2025-04-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(choices=[('XG', 'XG'), ('G', 'G'), ('M', 'M')], default='XG', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
