# Generated by Django 5.2 on 2025-04-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_image_products_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
        migrations.AddField(
            model_name='products',
            name='model',
            field=models.CharField(choices=[('Bellafral', 'Bellafral'), ('Big Confort', 'Big Confort'), ('Basic/Mille', 'Basic/Mille')], default='Bellafral', max_length=200),
        ),
    ]
