# Generated by Django 5.2 on 2025-04-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_description_alter_products_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(blank=True, default=0, max_length=6, null=True),
        ),
    ]
